import Link from "next/link";
import type { Metadata } from "next";
import "./globals.css";
import "react-datepicker/dist/react-datepicker.css";

import { IoHomeOutline } from "react-icons/io5";
import { IoTicketOutline } from "react-icons/io5";
import { HiOutlineUsers } from "react-icons/hi";
import { IoPower } from "react-icons/io5";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const menuList = [
  {
    title: "ダッシュボード",
    path: "/dashboard",
    icon: IoHomeOutline,
  },
  {
    title: "すべてのタスク",
    path: "/dashboard/tasks",
    icon: IoTicketOutline,
  },
  {
    title: "ユーザ別タスク",
    path: "/dashboard/users",
    icon: HiOutlineUsers,
  },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
